### ISSUE TITLE
Seems stuck at the end?

### ISSUE THREAD

**Issue by SteveW25561** [thhan/Docker-PiShrink#1]
This is terrific - I couldn't get the virtual box methods to work and it's a major resource hog, so this is amazing - thanks! I just ran it, and right now, my Mac's terminal output is stuck at this line:

```
Creating new /etc/rc.local

retropie: 157430/7616736 files (0.1% non-contiguous), 1635363/31245056 blocks

resize2fs 1.42.12 (29-Aug-2014)

resize2fs 1.42.12 (29-Aug-2014)

Resizing the filesystem on /dev/loop0 to 1630480 (4k) blocks.

Begin pass 2 (max = 466514)

Relocating blocks XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Begin pass 3 (max = 954)

Scanning inode table XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Begin pass 4 (max = 18702)

Updating inode references XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

The filesystem on /dev/loop0 is now 1630480 (4k) blocks long.

```
It doesn't seem to finish with final statement of : `"Shrunk pi.img from xx size to xx size" `and I'm still sitting at a blank line, not a command prompt. Is the script finished, or should I wait even longer? It's been sitting there for an hour.

**Comment by y4roc** [comment]
Sorry, I can't reproduce your issue.
